name: Scrape movie info

on:
  push:
    paths:
      - "Movies.txt"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install dependencies
        run: |
          pip install numpy rottentomatoes

      - name: Scrape movie info
        run: python rt_scrape.py

      - name: Commit results
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "auto update"
          git push
